CALCAPP.PGM: CALCULATOR_CONTROLLER.PGM.RPGLE QPROTOSRC/CALCULATOR_VIEW.RPGLEINC QPROTOSRC/CALCULATOR_MODEL.RPGLEINC CALCDIR.BNDDIR

VALFUNCS.MODULE: VALIDATION_FUNCTIONS.RPGLE QPROTOSRC/VALIDATION_FUNCTIONS.RPGLEINC
MATH100.MODULE: MATH100.RPGLE QPROTOSRC/MATH100.RPGLEINC
CALCVW.MODULE: CALCULATOR_VIEW.RPGLE QPROTOSRC/CALCULATOR_VIEW.RPGLEINC
CALCMDL.MODULE: CALCULATOR_MODEL.RPGLE QPROTOSRC/CALCULATOR_MODEL.RPGLEINC





