VALFUNCS.SRVPGM: VALFUNCS.BND VALFUNCS.MODULE
VALFUNCS.SRVPGM: TEXT = SRVPGM Validation Functions

MATH100.SRVPGM: MATH100.BND MATH100.MODULE
MATH100.SRVPGM: TEXT = SRVPGM Arithmetic Operations

CALCMDLSV.SRVPGM: CALCULATOR_MODEL.BND CALCMDL.MODULE VALFUNCS.SRVPGM MATH100.SRVPGM 
CALCMDLSV.SRVPGM: TEXT = SRVPGM Calculator Model

CALCVWSV.SRVPGM: CALCULATOR_VIEW.BND CALCVW.MODULE
CALCVWSV.SRVPGM: TEXT = SRVPGM Calculator View


